# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim
WORKDIR /app

# Install dependencies
COPY pyproject.toml requirements.txt ./
RUN pip install --no-cache-dir fastmcp==2.3.3 google-api-python-client>=2.169.0 google-auth-httplib2>=0.2.0 google-auth-oauthlib>=1.2.2 python-dotenv requests

# Copy source code
COPY . .

# Default command
CMD ["python", "main.py"]
